// ============================================================
// 계정과목 표준 마스터 — 개인사업자/법인사업자 공통
// 출처: 계정과목 PDF (제1기: 2025.01.01 ~ 2025.12.31)
// 412 서비스수입(개인 전용)은 제외 — 공통 마스터 정책
// ============================================================

export type AccountCategory =
  | '일반' | '예금' | '유가증권' | '차감'
  | '일반재고' | '환출차감' | '할인차감' | '관세차감' | '공정재고'
  | '비상각' | '상각' | '임시'
  | '차입금' | '사채차입금' | '충당금' | '준비금' | '증가'
  | '자본금' | '자본잉여금' | '법정적립금' | '임의적립금' | '미처분이익' | '차기이월'
  | '매출' | '환입차감' | '매입판매' | '용역' | '분양판매' | '제조집합' | '제조판매'
  | '원재료비' | '부재료비' | '경비' | '기타'
  | '노무비(직원근로)' | '노무비(직원퇴직)'
  | '인건비(임원근로)' | '인건비(근로)' | '인건비(일용)' | '인건비(퇴직)'
  | '수입이자' | '지급이자'
  | '준비금환입' | '준비금전입' | '처분손실'
  | '평가이익' | '평가손실'
  | '중단직접비용' | '손상차손' | '손상환입'
  | '';

export interface AccountMasterEntry {
  code: string;
  name: string;
  category: AccountCategory;
}

// ── 표준 계정과목 마스터 (412 제외) ──
export const ACCOUNT_MASTER: readonly AccountMasterEntry[] = [
  // 당좌자산
  { code: '101', name: '현금', category: '일반' },
  { code: '102', name: '당좌예금', category: '예금' },
  { code: '103', name: '보통예금', category: '예금' },
  { code: '104', name: '기타제예금', category: '예금' },
  { code: '105', name: '정기예.적금', category: '예금' },
  { code: '106', name: '기타단기금융상품', category: '예금' },
  { code: '107', name: '단기매매증권', category: '유가증권' },
  { code: '108', name: '외상매출금', category: '일반' },
  { code: '109', name: '대손충당금', category: '차감' },
  { code: '110', name: '받을어음', category: '일반' },
  { code: '111', name: '대손충당금', category: '차감' },
  { code: '112', name: '공사미수금', category: '일반' },
  { code: '113', name: '대손충당금', category: '차감' },
  { code: '114', name: '단기대여금', category: '일반' },
  { code: '115', name: '대손충당금', category: '차감' },
  { code: '116', name: '미수수익', category: '일반' },
  { code: '117', name: '대손충당금', category: '차감' },
  { code: '118', name: '분양미수금', category: '일반' },
  { code: '119', name: '대손충당금', category: '차감' },
  { code: '120', name: '미수금', category: '일반' },
  { code: '121', name: '대손충당금', category: '차감' },
  { code: '123', name: '매도가능증권', category: '유가증권' },
  { code: '124', name: '만기보유증권', category: '유가증권' },
  { code: '131', name: '선급금', category: '일반' },
  { code: '132', name: '대손충당금', category: '차감' },
  { code: '133', name: '선급비용', category: '일반' },
  { code: '134', name: '가지급금', category: '일반' },
  { code: '135', name: '부가세대급금', category: '일반' },
  { code: '136', name: '선납세금', category: '일반' },
  { code: '137', name: '주.임.종단기채권', category: '일반' },
  { code: '138', name: '전도금', category: '일반' },
  { code: '139', name: '선급공사비', category: '일반' },
  { code: '140', name: '이연법인세자산', category: '일반' },

  // 재고자산
  { code: '146', name: '상품', category: '일반재고' },
  { code: '147', name: '매입환출및에누리', category: '환출차감' },
  { code: '148', name: '매입할인', category: '할인차감' },
  { code: '149', name: '관세환급금', category: '관세차감' },
  { code: '150', name: '제품', category: '일반재고' },
  { code: '151', name: '관세환급금', category: '관세차감' },
  { code: '152', name: '완성건물', category: '일반재고' },
  { code: '153', name: '원재료', category: '일반재고' },
  { code: '154', name: '매입환출및에누리', category: '환출차감' },
  { code: '155', name: '매입할인', category: '할인차감' },
  { code: '156', name: '원재료(도급)', category: '일반재고' },
  { code: '157', name: '매입환출및에누리', category: '환출차감' },
  { code: '158', name: '매입할인', category: '할인차감' },
  { code: '159', name: '원재료(분양)', category: '일반재고' },
  { code: '160', name: '매입환출및에누리', category: '환출차감' },
  { code: '161', name: '매입할인', category: '할인차감' },
  { code: '162', name: '부재료', category: '일반재고' },
  { code: '163', name: '매입환출및에누리', category: '환출차감' },
  { code: '164', name: '매입할인', category: '할인차감' },
  { code: '165', name: '건설용지', category: '일반재고' },
  { code: '166', name: '가설재', category: '일반재고' },
  { code: '167', name: '저장품', category: '일반재고' },
  { code: '168', name: '미착품', category: '일반재고' },
  { code: '169', name: '재공품', category: '공정재고' },
  { code: '170', name: '미완성공사(도급)', category: '공정재고' },
  { code: '171', name: '미완성공사(분양)', category: '공정재고' },
  { code: '172', name: '소모품', category: '일반재고' },

  // 투자자산
  { code: '176', name: '장기성예금', category: '예금' },
  { code: '177', name: '특정현금과예금', category: '예금' },
  { code: '178', name: '매도가능증권', category: '유가증권' },
  { code: '179', name: '장기대여금', category: '일반' },
  { code: '180', name: '대손충당금', category: '차감' },
  { code: '181', name: '만기보유증권', category: '유가증권' },
  { code: '182', name: '지분법적용투자주식', category: '일반' },
  { code: '187', name: '투자부동산', category: '일반' },
  { code: '192', name: '단체퇴직보험예치금', category: '일반' },
  { code: '197', name: '투자일임계약자산', category: '일반' },
  { code: '198', name: '퇴직연금운용자산', category: '일반' },
  { code: '199', name: '퇴직보험예치금', category: '일반' },
  { code: '200', name: '국민연금전환금', category: '일반' },

  // 유형자산
  { code: '201', name: '토지', category: '비상각' },
  { code: '202', name: '건물', category: '상각' },
  { code: '203', name: '감가상각누계액', category: '차감' },
  { code: '204', name: '구축물', category: '상각' },
  { code: '205', name: '감가상각누계액', category: '차감' },
  { code: '206', name: '기계장치', category: '상각' },
  { code: '207', name: '감가상각누계액', category: '차감' },
  { code: '208', name: '차량운반구', category: '상각' },
  { code: '209', name: '감가상각누계액', category: '차감' },
  { code: '210', name: '공구와기구', category: '상각' },
  { code: '211', name: '감가상각누계액', category: '차감' },
  { code: '212', name: '비품', category: '상각' },
  { code: '213', name: '감가상각누계액', category: '차감' },
  { code: '214', name: '건설중인자산', category: '임시' },
  { code: '215', name: '미착기계', category: '상각' },
  { code: '216', name: '감가상각누계액', category: '차감' },
  { code: '217', name: '건설용장비', category: '상각' },
  { code: '218', name: '감가상각누계액', category: '차감' },

  // 무형자산
  { code: '231', name: '영업권', category: '일반' },
  { code: '232', name: '특허권', category: '일반' },
  { code: '233', name: '상표권', category: '일반' },
  { code: '234', name: '실용신안권', category: '일반' },
  { code: '235', name: '의장권', category: '일반' },
  { code: '236', name: '면허권', category: '일반' },
  { code: '237', name: '광업권', category: '일반' },
  { code: '238', name: '창업비', category: '일반' },
  { code: '239', name: '개발비', category: '일반' },
  { code: '240', name: '소프트웨어', category: '일반' },

  // 유동부채
  { code: '251', name: '외상매입금', category: '일반' },
  { code: '252', name: '지급어음', category: '일반' },
  { code: '253', name: '미지급금', category: '일반' },
  { code: '254', name: '예수금', category: '일반' },
  { code: '255', name: '부가세예수금', category: '일반' },
  { code: '256', name: '당좌차월', category: '차입금' },
  { code: '257', name: '가수금', category: '일반' },
  { code: '258', name: '예수보증금', category: '일반' },
  { code: '259', name: '선수금', category: '일반' },
  { code: '260', name: '단기차입금', category: '차입금' },
  { code: '261', name: '미지급세금', category: '일반' },
  { code: '262', name: '미지급비용', category: '일반' },
  { code: '263', name: '선수수익', category: '일반' },
  { code: '264', name: '유동성장기부채', category: '차입금' },
  { code: '265', name: '미지급배당금', category: '일반' },
  { code: '266', name: '지급보증채무', category: '일반' },
  { code: '267', name: '수출금융', category: '일반' },
  { code: '268', name: '수입금융', category: '일반' },
  { code: '269', name: '공사손실충당금', category: '일반' },
  { code: '270', name: '하자보수충당금', category: '일반' },
  { code: '271', name: '공사선수금', category: '일반' },
  { code: '272', name: '분양선수금', category: '일반' },
  { code: '273', name: '이연법인세부채', category: '일반' },

  // 비유동부채
  { code: '291', name: '사채', category: '사채차입금' },
  { code: '292', name: '사채할인발행차금', category: '차감' },
  { code: '293', name: '장기차입금', category: '차입금' },
  { code: '294', name: '임대보증금', category: '일반' },
  { code: '295', name: '퇴직급여충당부채', category: '충당금' },
  { code: '296', name: '퇴직보험충당부채', category: '충당금' },
  { code: '297', name: '장기미지급금', category: '일반' },
  { code: '298', name: '중소기업투자준비금', category: '준비금' },
  { code: '299', name: '기술개발준비금', category: '준비금' },
  { code: '300', name: '해외시장개척준비금', category: '준비금' },
  { code: '301', name: '지방이전준비금', category: '준비금' },
  { code: '302', name: '수출손실준비금', category: '준비금' },
  { code: '303', name: '주.임.종장기차입금', category: '차입금' },
  { code: '304', name: '관계회사장기차입금', category: '차입금' },
  { code: '305', name: '외화장기차입금', category: '차입금' },
  { code: '306', name: '장기공사선수금', category: '일반' },
  { code: '307', name: '장기임대보증금', category: '일반' },
  { code: '308', name: '장기성지급어음', category: '일반' },
  { code: '309', name: '환율조정대', category: '일반' },
  { code: '310', name: '이연법인세부채', category: '일반' },
  { code: '311', name: '신주인수권부사채', category: '사채차입금' },
  { code: '312', name: '전환사채', category: '사채차입금' },
  { code: '313', name: '사채할증발행차금', category: '증가' },
  { code: '314', name: '장기제품보증부채', category: '충당금' },
  { code: '329', name: '퇴직연금충당부채', category: '충당금' },
  { code: '330', name: '퇴직연금미지급금', category: '충당금' },

  // 자본금·자본잉여금
  { code: '331', name: '자본금', category: '자본금' },
  { code: '332', name: '우선주자본금', category: '자본금' },
  { code: '337', name: '출자금', category: '자본금' },
  { code: '338', name: '인출금', category: '자본금' },
  { code: '341', name: '주식발행초과금', category: '자본잉여금' },
  { code: '342', name: '감자차익', category: '자본잉여금' },
  { code: '343', name: '자기주식처분이익', category: '자본잉여금' },
  { code: '344', name: '전환권대가', category: '자본잉여금' },
  { code: '345', name: '신주인수권대가', category: '자본잉여금' },
  { code: '349', name: '기타자본잉여금', category: '자본잉여금' },
  { code: '350', name: '재평가적립금', category: '자본잉여금' },

  // 이익잉여금
  { code: '351', name: '이익준비금', category: '법정적립금' },
  { code: '352', name: '기업합리화적립금', category: '법정적립금' },
  { code: '353', name: '법정적립금임의설정', category: '법정적립금' },
  { code: '354', name: '재무구조개선적립금', category: '법정적립금' },
  { code: '355', name: '임의적립금', category: '임의적립금' },
  { code: '356', name: '사업확장적립금', category: '임의적립금' },
  { code: '357', name: '감채적립금', category: '임의적립금' },
  { code: '358', name: '배당평균적립금', category: '임의적립금' },
  { code: '359', name: '주식할인발행차상각', category: '미처분이익' },
  { code: '360', name: '배당건설이자상각', category: '미처분이익' },
  { code: '361', name: '상환주식의상환액', category: '미처분이익' },
  { code: '362', name: '자기주식처분손잔액', category: '미처분이익' },
  { code: '363', name: '중소기업투자준비금', category: '임의적립금' },
  { code: '364', name: '기술개발준비금', category: '임의적립금' },
  { code: '365', name: '해외시장개척준비금', category: '임의적립금' },
  { code: '366', name: '지방이전준비금', category: '임의적립금' },
  { code: '367', name: '수출손실준비금', category: '임의적립금' },
  { code: '368', name: '기타임의적립금', category: '임의적립금' },
  { code: '369', name: '회계변경의누적효과', category: '미처분이익' },
  { code: '370', name: '전기오류수정이익', category: '미처분이익' },
  { code: '371', name: '전기오류수정손실', category: '미처분이익' },
  { code: '372', name: '중간배당금', category: '미처분이익' },
  { code: '374', name: '기타이익잉여금', category: '미처분이익' },
  { code: '375', name: '이월이익잉여금', category: '차기이월' },
  { code: '376', name: '이월결손금', category: '차기이월' },
  { code: '377', name: '미처분이익잉여금', category: '차기이월' },
  { code: '378', name: '미처리결손금', category: '차기이월' },
  { code: '379', name: '당기순이익', category: '차기이월' },
  { code: '380', name: '당기순손실', category: '차기이월' },
  { code: '381', name: '주식할인발행차금', category: '차감' },
  { code: '382', name: '배당건설이자', category: '차감' },
  { code: '383', name: '자기주식', category: '차감' },
  { code: '386', name: '신주발행비', category: '차감' },
  { code: '387', name: '미교부주식배당금', category: '증가' },
  { code: '388', name: '신주청약증거금', category: '증가' },
  { code: '392', name: '국고보조금', category: '증가' },
  { code: '393', name: '공사부담금', category: '증가' },
  { code: '394', name: '감자차손', category: '차감' },
  { code: '395', name: '자기주식처분손실', category: '차감' },
  { code: '396', name: '주식매입선택권', category: '증가' },

  // 손익·매출
  { code: '400', name: '손익', category: '' },
  { code: '401', name: '상품매출', category: '매출' },
  { code: '402', name: '매출환입및에누리', category: '환입차감' },
  { code: '403', name: '매출할인', category: '할인차감' },
  { code: '404', name: '제품매출', category: '매출' },
  { code: '405', name: '매출환입및에누리', category: '환입차감' },
  { code: '406', name: '매출할인', category: '할인차감' },
  { code: '407', name: '공사수입금', category: '매출' },
  { code: '408', name: '매출할인', category: '할인차감' },
  { code: '409', name: '완성건물매출', category: '매출' },
  { code: '410', name: '매출할인', category: '할인차감' },
  { code: '411', name: '임대료수입', category: '매출' },
  // 412: 서비스수입(개인 전용) — 제외

  // 매출원가
  { code: '451', name: '상품매출원가', category: '매입판매' },
  { code: '452', name: '도급공사매출원가', category: '용역' },
  { code: '453', name: '분양공사매출원가', category: '분양판매' },
  { code: '454', name: '제조', category: '제조집합' },
  { code: '455', name: '제품매출원가', category: '제조판매' },
  { code: '456', name: '분양제조', category: '제조집합' },

  // 제조경비 (5xx)
  { code: '501', name: '원재료비', category: '원재료비' },
  { code: '502', name: '부재료비', category: '부재료비' },
  { code: '503', name: '급여', category: '노무비(직원근로)' },
  { code: '504', name: '임금', category: '노무비(직원근로)' },
  { code: '505', name: '상여금', category: '노무비(직원근로)' },
  { code: '506', name: '제수당', category: '노무비(직원근로)' },
  { code: '507', name: '잡급', category: '노무비(직원근로)' },
  { code: '508', name: '퇴직급여', category: '노무비(직원퇴직)' },
  { code: '509', name: '퇴직보험충당금전입', category: '노무비(직원퇴직)' },
  { code: '510', name: '퇴직급여', category: '노무비(직원퇴직)' },
  { code: '511', name: '복리후생비', category: '경비' },
  { code: '512', name: '여비교통비', category: '경비' },
  { code: '513', name: '접대비(기업업무추진비)', category: '경비' },
  { code: '514', name: '통신비', category: '경비' },
  { code: '515', name: '가스수도료', category: '경비' },
  { code: '516', name: '전력비', category: '경비' },
  { code: '517', name: '세금과공과금', category: '경비' },
  { code: '518', name: '감가상각비', category: '경비' },
  { code: '519', name: '지급임차료', category: '경비' },
  { code: '520', name: '수선비', category: '경비' },
  { code: '521', name: '보험료', category: '경비' },
  { code: '522', name: '차량유지비', category: '경비' },
  { code: '523', name: '경상연구개발비', category: '경비' },
  { code: '524', name: '운반비', category: '경비' },
  { code: '525', name: '교육훈련비', category: '경비' },
  { code: '526', name: '도서인쇄비', category: '경비' },
  { code: '527', name: '회의비', category: '경비' },
  { code: '528', name: '포장비', category: '경비' },
  { code: '529', name: '사무용품비', category: '경비' },
  { code: '530', name: '소모품비', category: '경비' },
  { code: '531', name: '지급수수료', category: '경비' },
  { code: '532', name: '보관료', category: '경비' },
  { code: '533', name: '외주가공비', category: '경비' },
  { code: '534', name: '시험비', category: '경비' },
  { code: '535', name: '기밀비', category: '경비' },
  { code: '536', name: '잡비', category: '경비' },
  { code: '549', name: '명예퇴직금', category: '노무비(직원퇴직)' },

  // 도급공사 제조경비 (6xx)
  { code: '601', name: '원재료비', category: '원재료비' },
  { code: '602', name: '외주비', category: '기타' },
  { code: '603', name: '급여', category: '노무비(직원근로)' },
  { code: '604', name: '임금', category: '노무비(직원근로)' },
  { code: '605', name: '상여금', category: '노무비(직원근로)' },
  { code: '606', name: '제수당', category: '노무비(직원근로)' },
  { code: '607', name: '퇴직급여', category: '노무비(직원퇴직)' },
  { code: '608', name: '퇴직보험충당금전입', category: '노무비(직원퇴직)' },
  { code: '609', name: '퇴직급여', category: '노무비(직원퇴직)' },
  { code: '610', name: '중기및운반비', category: '기타' },
  { code: '611', name: '복리후생비', category: '경비' },
  { code: '612', name: '여비교통비', category: '경비' },
  { code: '613', name: '접대비(기업업무추진비)', category: '경비' },
  { code: '614', name: '통신비', category: '경비' },
  { code: '615', name: '가스수도료', category: '경비' },
  { code: '616', name: '전력비', category: '경비' },
  { code: '617', name: '세금과공과금', category: '경비' },
  { code: '618', name: '감가상각비', category: '경비' },
  { code: '619', name: '지급임차료', category: '경비' },
  { code: '620', name: '수선비', category: '경비' },
  { code: '621', name: '보험료', category: '경비' },
  { code: '622', name: '차량유지비', category: '경비' },
  { code: '623', name: '운반비', category: '경비' },
  { code: '624', name: '잡자재대', category: '경비' },
  { code: '625', name: '교육훈련비', category: '경비' },
  { code: '626', name: '도서인쇄비', category: '경비' },
  { code: '627', name: '하자보수비', category: '경비' },
  { code: '628', name: '포장비', category: '경비' },
  { code: '629', name: '사무용품비', category: '경비' },
  { code: '630', name: '소모품비', category: '경비' },
  { code: '631', name: '지급수수료', category: '경비' },
  { code: '632', name: '보관료', category: '경비' },
  { code: '633', name: '외주가공비', category: '경비' },
  { code: '634', name: '장비사용료', category: '경비' },
  { code: '635', name: '설계용역비', category: '경비' },
  { code: '636', name: '광고선전비', category: '경비' },
  { code: '637', name: '소모공구비', category: '경비' },
  { code: '638', name: '외주공사비', category: '경비' },
  { code: '639', name: '협회비', category: '경비' },
  { code: '640', name: '잡비', category: '경비' },
  { code: '641', name: '공사손실충당금전입', category: '기타' },
  { code: '642', name: '공사손실충당금환입', category: '기타' },
  { code: '649', name: '명예퇴직금', category: '노무비(직원퇴직)' },

  // 분양공사 제조경비 (7xx)
  { code: '701', name: '원재료비', category: '원재료비' },
  { code: '702', name: '중기및운반비', category: '기타' },
  { code: '703', name: '급여', category: '노무비(직원근로)' },
  { code: '704', name: '임금', category: '노무비(직원근로)' },
  { code: '705', name: '상여금', category: '노무비(직원근로)' },
  { code: '706', name: '제수당', category: '노무비(직원근로)' },
  { code: '707', name: '퇴직급여', category: '노무비(직원퇴직)' },
  { code: '708', name: '퇴직보험충당금전입', category: '노무비(직원퇴직)' },
  { code: '709', name: '퇴직급여', category: '노무비(직원퇴직)' },
  { code: '710', name: '건설용지비', category: '기타' },
  { code: '711', name: '복리후생비', category: '경비' },
  { code: '712', name: '여비교통비', category: '경비' },
  { code: '713', name: '접대비(기업업무추진비)', category: '경비' },
  { code: '714', name: '통신비', category: '경비' },
  { code: '715', name: '가스수도료', category: '경비' },
  { code: '716', name: '전력비', category: '경비' },
  { code: '717', name: '세금과공과금', category: '경비' },
  { code: '718', name: '감가상각비', category: '경비' },
  { code: '719', name: '지급임차료', category: '경비' },
  { code: '720', name: '수선비', category: '경비' },
  { code: '721', name: '보험료', category: '경비' },
  { code: '722', name: '차량유지비', category: '경비' },
  { code: '723', name: '경상연구개발비', category: '경비' },
  { code: '724', name: '잡자재대', category: '경비' },
  { code: '725', name: '교육훈련비', category: '경비' },
  { code: '726', name: '도서인쇄비', category: '경비' },
  { code: '727', name: '회의비', category: '경비' },
  { code: '728', name: '포장비', category: '경비' },
  { code: '729', name: '사무용품비', category: '경비' },
  { code: '730', name: '소모품비', category: '경비' },
  { code: '731', name: '지급수수료', category: '경비' },
  { code: '732', name: '보관료', category: '경비' },
  { code: '733', name: '외주가공비', category: '경비' },
  { code: '734', name: '시험비', category: '경비' },
  { code: '735', name: '설계용역비', category: '경비' },
  { code: '736', name: '가설재손료', category: '경비' },
  { code: '737', name: '잡비', category: '경비' },
  { code: '741', name: '공사손실충당금전입', category: '기타' },
  { code: '742', name: '공사손실충당금환입', category: '기타' },
  { code: '743', name: '외주비', category: '기타' },
  { code: '749', name: '명예퇴직금', category: '노무비(직원퇴직)' },

  // 판매비와 관리비 (8xx)
  { code: '801', name: '임원급여', category: '인건비(임원근로)' },
  { code: '802', name: '직원급여', category: '인건비(근로)' },
  { code: '803', name: '상여금', category: '인건비(근로)' },
  { code: '804', name: '제수당', category: '인건비(근로)' },
  { code: '805', name: '잡급', category: '인건비(일용)' },
  { code: '806', name: '퇴직급여', category: '인건비(퇴직)' },
  { code: '807', name: '퇴직보험충당금전입', category: '인건비(퇴직)' },
  { code: '808', name: '퇴직급여', category: '인건비(퇴직)' },
  { code: '811', name: '복리후생비', category: '경비' },
  { code: '812', name: '여비교통비', category: '경비' },
  { code: '813', name: '접대비(기업업무추진비)', category: '경비' },
  { code: '814', name: '통신비', category: '경비' },
  { code: '815', name: '수도광열비', category: '경비' },
  { code: '816', name: '전력비', category: '경비' },
  { code: '817', name: '세금과공과금', category: '경비' },
  { code: '818', name: '감가상각비', category: '경비' },
  { code: '819', name: '지급임차료', category: '경비' },
  { code: '820', name: '수선비', category: '경비' },
  { code: '821', name: '보험료', category: '경비' },
  { code: '822', name: '차량유지비', category: '경비' },
  { code: '823', name: '경상연구개발비', category: '경비' },
  { code: '824', name: '운반비', category: '경비' },
  { code: '825', name: '교육훈련비', category: '경비' },
  { code: '826', name: '도서인쇄비', category: '경비' },
  { code: '827', name: '회의비', category: '경비' },
  { code: '828', name: '포장비', category: '경비' },
  { code: '829', name: '사무용품비', category: '경비' },
  { code: '830', name: '소모품비', category: '경비' },
  { code: '831', name: '지급수수료', category: '경비' },
  { code: '832', name: '보관료', category: '경비' },
  { code: '833', name: '광고선전비', category: '경비' },
  { code: '834', name: '판매촉진비', category: '경비' },
  { code: '835', name: '대손상각비', category: '경비' },
  { code: '836', name: '기밀비', category: '경비' },
  { code: '837', name: '건물관리비', category: '경비' },
  { code: '838', name: '수출제비용', category: '경비' },
  { code: '839', name: '판매수수료', category: '경비' },
  { code: '840', name: '무형고정자산상각', category: '경비' },
  { code: '841', name: '환가료', category: '경비' },
  { code: '842', name: '견본비', category: '경비' },
  { code: '843', name: '해외접대비(기업업무추진비)', category: '경비' },
  { code: '844', name: '해외시장개척비', category: '경비' },
  { code: '845', name: '미분양주택관리비', category: '경비' },
  { code: '846', name: '수주비', category: '경비' },
  { code: '847', name: '하자보수충당금전입', category: '경비' },
  { code: '848', name: '잡비', category: '경비' },
  { code: '849', name: '명예퇴직금', category: '인건비(퇴직)' },
  { code: '850', name: '대손충당금환입', category: '준비금환입' },
  { code: '851', name: '퇴직급여충당부채환입', category: '준비금환입' },

  // 영업외수익 (9xx)
  { code: '901', name: '이자수익', category: '수입이자' },
  { code: '902', name: '만기보유증권이자', category: '수입이자' },
  { code: '903', name: '배당금수익', category: '일반' },
  { code: '904', name: '수입임대료', category: '일반' },
  { code: '905', name: '단기투자자산평가익', category: '일반' },
  { code: '906', name: '단기투자자산처분익', category: '일반' },
  { code: '907', name: '외환차익', category: '일반' },
  { code: '908', name: '대손충당금환입', category: '일반' },
  { code: '909', name: '수입수수료', category: '일반' },
  { code: '910', name: '외화환산이익', category: '일반' },
  { code: '911', name: '사채상환이익', category: '일반' },
  { code: '912', name: '전기오류수정이익', category: '일반' },
  { code: '913', name: '하자보수충당금환입', category: '일반' },
  { code: '914', name: '유형자산처분이익', category: '일반' },
  { code: '915', name: '투자자산처분이익', category: '일반' },
  { code: '916', name: '상각채권추심이익', category: '일반' },
  { code: '917', name: '자산수증이익', category: '일반' },
  { code: '918', name: '채무면제이익', category: '일반' },
  { code: '919', name: '보험차익', category: '일반' },
  { code: '920', name: '투자증권손상차환입', category: '일반' },
  { code: '921', name: '지분법이익', category: '일반' },
  { code: '924', name: '중소투자준비금환입', category: '준비금환입' },
  { code: '925', name: '기술개발준비금환입', category: '준비금환입' },
  { code: '926', name: '해외개척준비금환입', category: '준비금환입' },
  { code: '927', name: '지방이전준비금환입', category: '준비금환입' },
  { code: '928', name: '수출손실준비금환입', category: '준비금환입' },
  { code: '930', name: '잡이익', category: '일반' },

  // 영업외비용
  { code: '931', name: '이자비용', category: '지급이자' },
  { code: '932', name: '외환차손', category: '일반' },
  { code: '933', name: '기부금', category: '일반' },
  { code: '934', name: '기타의대손상각비', category: '일반' },
  { code: '935', name: '외화환산손실', category: '일반' },
  { code: '936', name: '매출채권처분손실', category: '일반' },
  { code: '937', name: '단기투자자산평가손', category: '일반' },
  { code: '938', name: '단기투자자산처분손', category: '일반' },
  { code: '939', name: '재고자산감모손실', category: '일반' },
  { code: '940', name: '재고자산평가손실', category: '일반' },
  { code: '941', name: '재해손실', category: '일반' },
  { code: '942', name: '전기오류수정손실', category: '일반' },
  { code: '943', name: '투자증권손상차손', category: '일반' },
  { code: '944', name: '지분법손실', category: '일반' },
  { code: '947', name: '회사채이자', category: '지급이자' },
  { code: '948', name: '사채상환손실', category: '일반' },
  { code: '949', name: '보상비', category: '일반' },
  { code: '950', name: '유형자산처분손실', category: '일반' },
  { code: '951', name: '투자자산처분손실', category: '일반' },
  { code: '952', name: '중소투자준비금전입', category: '준비금전입' },
  { code: '953', name: '기술개발준비금전입', category: '준비금전입' },
  { code: '954', name: '해외개척준비금전입', category: '준비금전입' },
  { code: '955', name: '지방이전준비금전입', category: '준비금전입' },
  { code: '956', name: '수출손실준비금전입', category: '준비금전입' },
  { code: '957', name: '특별상각', category: '처분손실' },
  { code: '960', name: '잡손실', category: '일반' },
  { code: '961', name: '이연법인세자산', category: '일반' },

  // 기타 보증금·장기채권 등
  { code: '962', name: '임차보증금', category: '일반' },
  { code: '963', name: '전세권', category: '일반' },
  { code: '964', name: '기타보증금', category: '일반' },
  { code: '965', name: '장기외상매출금', category: '일반' },
  { code: '966', name: '현재가치할인차금', category: '차감' },
  { code: '967', name: '대손충당금', category: '차감' },
  { code: '968', name: '장기받을어음', category: '일반' },
  { code: '969', name: '현재가치할인차금', category: '차감' },
  { code: '970', name: '대손충당금', category: '차감' },
  { code: '971', name: '장기미수금', category: '일반' },
  { code: '972', name: '현재가치할인차금', category: '차감' },
  { code: '973', name: '대손충당금', category: '차감' },
  { code: '974', name: '장기선급비용', category: '일반' },
  { code: '975', name: '장기선급금', category: '일반' },
  { code: '976', name: '부도어음과수표', category: '일반' },
  { code: '977', name: '대손충당금', category: '차감' },
  { code: '978', name: '전신전화가입권', category: '일반' },

  // 자본조정·기타포괄손익
  { code: '981', name: '매도가능증권평가익', category: '평가이익' },
  { code: '982', name: '매도가능증권평가손', category: '평가손실' },
  { code: '983', name: '해외사업환산이익', category: '평가이익' },
  { code: '984', name: '해외사업환산손실', category: '평가손실' },
  { code: '985', name: '파생상품평가이익', category: '평가이익' },
  { code: '986', name: '파생상품평가손실', category: '평가손실' },

  // 중단사업·세금
  { code: '991', name: '사업중단직접비', category: '중단직접비용' },
  { code: '992', name: '중단사업자산손상차', category: '손상차손' },
  { code: '993', name: '중단사업손상차환입', category: '손상환입' },
  { code: '997', name: '중단손익', category: '' },
  { code: '998', name: '법인세등', category: '' },
  { code: '999', name: '소득세등', category: '' },
];

// ── 코드 → 계정과목명 (마스터에서 자동 생성) ──
export const CODE_TO_NAME: Readonly<Record<string, string>> = (() => {
  const m: Record<string, string> = {};
  for (const e of ACCOUNT_MASTER) m[e.code] = e.name;
  return m;
})();

// ── 코드 → 구분 (마스터에서 자동 생성) ──
export const CODE_TO_CATEGORY: Readonly<Record<string, AccountCategory>> = (() => {
  const m: Record<string, AccountCategory> = {};
  for (const e of ACCOUNT_MASTER) m[e.code] = e.category;
  return m;
})();

// ── 계정과목명 → 코드 (동명 중복 시 가장 큰 코드 우선; 판관비 8xx 우선) ──
export const NAME_TO_CODE_PRIMARY: Readonly<Record<string, string>> = (() => {
  const m: Record<string, string> = {};
  for (const e of ACCOUNT_MASTER) {
    const prev = m[e.name];
    if (!prev || e.code > prev) m[e.name] = e.code;
  }
  return m;
})();

// ── 계정과목명 → 모든 코드 (제조경비 5xx/6xx/7xx + 판관비 8xx 등 동명 다중 매핑 조회용) ──
export const NAME_TO_CODES_ALL: Readonly<Record<string, readonly string[]>> = (() => {
  const m: Record<string, string[]> = {};
  for (const e of ACCOUNT_MASTER) {
    if (!m[e.name]) m[e.name] = [];
    m[e.name].push(e.code);
  }
  return m;
})();
